# Generated by Django 4.1.2 on 2022-10-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_board_good_board_good'),
        ('users', '0002_remove_user_nick_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='good',
            field=models.ManyToManyField(related_name='good_boards', to='board.board'),
        ),
    ]
