# Generated by Django 4.1.2 on 2022-10-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_board_command'),
        ('users', '0003_user_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='command',
            field=models.ManyToManyField(related_name='user_command', to='board.board'),
        ),
        migrations.AlterField(
            model_name='user',
            name='good',
            field=models.ManyToManyField(related_name='user_good', to='board.board'),
        ),
    ]
