# Generated by Django 4.1.2 on 2022-10-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_command_alter_user_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='command',
        ),
    ]
